application: php-ooievaar
version: 1
runtime: php55
api_version: 1
threadsafe: yes

handlers:
# Serve images as static resources.
- url: /(.+\.(gif|png|jpg))$
  static_files: \1
  upload: .+\.(gif|png|jpg)$
  application_readable: true

# Serve php scripts.
- url: /Hoofdpagina
  script: /main.php
  
- url: /Over_Ons
  script: /overons.php
  
- url: /Opdrachten/Biologie
  script: /Opdrachten/Biologie/biologie.php
  
- url: /Opdrachten/Rekenen
  script: /Opdrachten/Rekenen/rekenen.php
  
- url: /Opdrachten/Nederlands
  script: /Opdrachten/Nederlands/nederlands.php
  
- url: /Opdrachten/Biologie
  script: /Opdrachten/Biologie/biologie.php
  
- url: /Opdrachten/Geschiedenis
  script: /Opdrachten/Geschiedenis/geschiedenis.php
  
- url: /Opdrachten/Engels
  script: /Opdrachten/Engels/engels.php
  